### PR TITLE
Fix devicePixelRatio issue for mousemove events.

### PR DESCRIPTION
**Pull request by shurcooL**
Commit 3450bb0e45b5dab1e6456046e446ecb05f36db3f introduced support for `devicePixelRatio` values other than 1 (e.g., Retina displays, or when your browser zoom level is not 100%, etc.).

It applied the `devicePixelRatio` multiplier for mouse `click` events, but not for `mousemove` events. This fixes that.

### CODE REVIEW

**Comment by pakastin** [comment]
Looks great, thank you for your contribution!

I'm at the airport returning from Web Summit: I'll merge this when I'm back home, so I don't forget to update gh-pages as well.

**Comment by shurcooL** [comment]
Sounds good, thanks for reviewing quickly!

**Comment by pakastin** [comment]
Thanks again, it's live now!

**Comment by pakastin** [comment]
Closes #9.

**Pull request merged**
